#version: '3'

x-common-settings: &common-settings
  restart: always
  networks: &networks
    - nginx-proxy

x-ports-mapping:
  networking:
    api-gw: &api-gw-ports
      - 8888:8080
  web-services:
    keycloak: &keycloak-ports
      - 8081:8080
    todos: &todos-ports
      - 8082:5000
  database:
    keycloak-db: &keycloak-db-ports
      - 7071:3306
    todos-mongodb-ports: &todos-mongodb-ports
      - 7072:27017
    todos-redis-ports: &todos-redis-ports
      - 7073:16379
  storage:
    minio: &minio-ports
      - 9001:9000


x-xx-mongo-db-env: &todos-mongodb-env
  MONGO_INITDB_ROOT_USERNAME: &mongo-db-user ${MONGO_INITDB_ROOT_USERNAME}
  MONGO_INITDB_ROOT_PASSWORD: &mongo-db-password ${MONGO_INITDB_ROOT_PASSWORD}

x-xxx-todos-env: &todos-env
  SECRET_KEY: ${TODOS_SECRET_KEY}
  FLASK_APP: todos_app
  MONGO_HOST: todos-mongodb
  MONGO_PORT: 27017
  MONGO_USER: *mongo-db-user
  MONGO_PASS: *mongo-db-password
  MONGO_NAME: todos
  REDIS_HOST: todos-redisdb

x-xxx-keycloak: &keycloak-env
  DB_VENDOR: mariadb
  DB_ADDR: keycloak-db
  DB_DATABASE: ${KEYCLOAK_DB_NAME}
  DB_USER: ${KEYCLOAK_DB_USER}
  DB_PASSWORD: ${KEYCLOAK_USER_DB_PASS}
  VIRTUAL_HOST: ${VIRTUAL_HOST}
  LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
  LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
  VIRTUAL_PORT: "8080"
  HTTPS_METHOD: redirect
  PROXY_ADDRESS_FORWARDING: "true" # <==== very important if you use reverse proxy
  KEYCLOAK_USER: ${KEYCLOAK_ADMIN_USERNAME}
  KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

x-xxx-keycloak-db: &keycloak--db-env
  MYSQL_ROOT_PASSWORD: &keycloak-db-password ${KEYCLOAK_DB_ROOT_PASS}
  MYSQL_DATABASE: &keycloak-db-database ${KEYCLOAK_DB_NAME}
  MYSQL_USER: &keycloak-db-user ${KEYCLOAK_DB_USER}
  MYSQL_PASSWORD: &keycloak-db-user-pass ${KEYCLOAK_DB_PASS}
  MYSQL_ROOT_HOST: "%"

x-xx-minio-keys: &minio-keys
  # TODO set me from .env
  MINIO_ACCESS_KEY: &minio-access-key ${MINIO_ACCESS_KEY}
  MINIO_SECRET_KEY: &minio-secret-key ${MINIO_ACCESS_PASSWORD}

x-minio-env: &minio-env
  <<: *minio-keys
  MINIO_STORAGE_ENDPOINT: "minio:9000"
  MINIO_STORAGE_USE_HTTPS: "False"
  MINIO_STORAGE_MEDIA_BUCKET_NAME: "dev.media.products.marketplace.bucket"
  MINIO_STORAGE_STATIC_BUCKET_NAME: "dev.static.products.marketplace.bucket"
  MINIO_STORAGE_EXTERNAL_URL: "http://storage.localhost:8888" # TODO MUST BE THE API GW

volumes:
  keycloak-db:
  storage:
  todos-redis:
  todos-mongodb:

networks:
  nginx-proxy:
    name: nginx-proxy

services:

  api-gw:
    container_name: api-gw-test
#    restart: always # TODO exclude from prox net?
    <<: *common-settings
    ports: *api-gw-ports
    build: ../api-gw
    environment:
      NGINX_PORT: 80 # TODO check unset
    volumes:
      - ../api-gw/default.conf:/etc/nginx/conf.d/default.conf

  keycloak:
    container_name: keycloak-test
    <<: *common-settings
    ports: *keycloak-ports
    image: wizzn/keycloak:12
    environment:
      <<: *keycloak-env
    depends_on:
      - keycloak-db-test

  keycloak-db:
    container_name: keycloak-db-test
    <<: *common-settings
    environment: *keycloak--db-env
    ports: *keycloak-db-ports
    build: ./mariadb
    volumes:
      - keycloak-db:/var/lib/mysql

  minio:
    <<: *common-settings
    environment: *minio-env
    ports: *minio-ports
    image: minio/minio:RELEASE.2020-05-16T01-33-21Z
    command: server /data
    volumes:
      - storage:/data

  todos:
    <<: *common-settings
    environment: *todos-env
    ports: *todos-ports
    image: todos
    build:
      context: ../todos
      dockerfile: ../todos/Dockerfile
    volumes:
      - ../todos/:/code

  todos-mongodb:
    <<: *common-settings
    environment: *todos-mongodb-env
    ports: *todos-mongodb-ports
    image: mongo
    volumes:
      - todos-mongodb:/data/db

  todos-redisdb:
    <<: *common-settings
    ports: *todos-redis-ports
    image: redis:5-alpine
    command: redis-server --appendonly yes
    volumes:
      - todos-redis:/data

  pma_user_db:
    container_name: pma-test
    <<: *common-settings
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: keycloak-db
      PMA_USER: *keycloak-db-user-pass
      PMA_PASSWORD: *keycloak-db-password
    ports:
      - 9999:80